name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: felipe-publio-cv.tex

      - name: Convert LaTeX to Markdown
        run: |
          sudo apt-get install -y pandoc
          pandoc felipe-publio-cv.tex -o felipe-publio-cv.md

      - name: Commit changes to current repository
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add felipe-publio-cv.pdf felipe-publio-cv.md
          git commit -m "Update PDF and Markdown files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone target repository
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/publi0/publio.dev.git target-repo

      - name: Copy PDF to target repository
        run: |
          cp felipe-publio-cv.pdf target-repo/files/

      - name: Commit and push changes to target repository
        run: |
          cd target-repo
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add files/felipe-publio-cv.pdf
          git commit -m "Update CV PDF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
